name: Create Image

on:
  push:
    branches:
      - main

jobs:
  create-image:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Set up Packer
        id: setup
        uses: hashicorp/setup-packer@main

      - name: Packer init
        id: init
        run: 'packer init .'

      - name: Packer fmt check
        id: fmt
        run: 'packer fmt -check .'

      - name: Packer validate
        id: validate
        run: 'packer validate -syntax-only -evaluate-datasources .'

      - name: Packer build
        env:
          PKR_VAR_domain: ${{ secrets.PKR_VAR_domain }}
          PKR_VAR_email: ${{ secrets.PKR_VAR_email }}
          PKR_VAR_jenkins_user: ${{ secrets.PKR_VAR_jenkins_user }}
          PKR_VAR_jenkins_password: ${{ secrets.PKR_VAR_jenkins_password }}
          PKR_VAR_docker_hub_username: ${{ secrets.PKR_VAR_docker_hub_username }}
          PKR_VAR_docker_hub_password: ${{ secrets.PKR_VAR_docker_hub_password }}
          PKR_VAR_github_token: ${{ secrets.PKR_VAR_github_token }}
        id: build
        run: packer build -color=false .
